// Equipo real de BG Consulting Group (docs/bgcg-site-content.txt). Nombres tal cual.
// lead: liderazgo, se destaca arriba; el resto va en grilla compacta.
export type Member = { name: string; es: string; en: string; lead?: boolean };

export const TEAM: Member[] = [
  { name: "Mario A. Cortés", es: "Co-CEO", en: "Co-CEO", lead: true },
  { name: "Edgardo Romero", es: "Co-CEO", en: "Co-CEO", lead: true },
  { name: "Rogelio Viloria Beltrán", es: "Co-CEO y CFO", en: "Co-CEO & CFO", lead: true },
  { name: "Luis Mateo", es: "COO", en: "COO", lead: true },
  { name: "Hugo García", es: "CIO", en: "CIO", lead: true },
  { name: "Diana Galicia Matuz", es: "Líder del área legal", en: "Legal Area Leader", lead: true },
  { name: "Brenda Borboa", es: "Trade Compliance Sr.", en: "Trade Compliance Sr." },
  { name: "Angélica Rodríguez", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Jonathan Morales", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Kevin García", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Dayanna Aldaz", es: "Abogada", en: "Lawyer" },
  { name: "Valeria Fernández", es: "Abogada", en: "Lawyer" },
  { name: "Azucena García", es: "Desarrolladora de escritorio", en: "Desktop Developer" },
  { name: "Alfredo Pérez", es: "Desarrollador web", en: "Web Developer" },
  { name: "José Muro", es: "Supervisor de TI", en: "IT Supervisor" },
  { name: "Edgar Aguilar", es: "Soporte de TI", en: "IT Support" },
  { name: "Arturo Alvarado", es: "BMS Consulting", en: "BMS Consulting" },
  { name: "Román Elizalde", es: "BMS Consulting", en: "BMS Consulting" },
  { name: "Karla González", es: "BMS Consulting", en: "BMS Consulting" },
  { name: "Paulina González", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Sandra Ornelas", es: "Especialista import-export", en: "Import-Export Specialist" },
  { name: "Roberto Morales", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Osiris Gómez", es: "Asesor contable", en: "Accounting Advisor" },
  { name: "Yaridt Rodríguez", es: "Asesor contable", en: "Accounting Advisor" },
  { name: "Maydeleni Roblero", es: "Asesor contable", en: "Accounting Advisor" },
  { name: "Emilia Varela", es: "Asesora legal", en: "Legal Advisor" },
  { name: "Sergio Romero", es: "3PL y logística", en: "3PL & Logistics" },
  { name: "Leonardo Arroyo Gómez", es: "Especialista OEA/CTPAT", en: "OEA/CTPAT Specialist" },
  { name: "Aylin Gil", es: "Project Management Jr.", en: "Project Management Jr." },
  { name: "Giselle García", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Jocelyn Vázquez", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Mireya Cisneros", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
  { name: "Lineth Alapisco", es: "Trade Compliance Jr.", en: "Trade Compliance Jr." },
];
